{% set pip_name = "avro" %}  # [py27]
{% set pip_name = "avro-python3" %}  # [py3k]
{% set version = "1.10.2" %}

package:
  name: python-avro
  version: {{ version }}

source:   # [py27 or py3k]
  # Avro exist as two versions in apache avro for py2 and py3k.
  fn: {{ pip_name }}-{{ version }}.tar.gz  # [py27]
  url: https://pypi.io/packages/source/{{ pip_name[0] }}/{{ pip_name }}/{{ pip_name }}-{{ version }}.tar.gz  # [py27]
  sha256: 381b990cc4c4444743c3297348ffd46e0c3a5d7a17e15b2f4a9042f6e955c31a  # [py27]

  fn: {{ pip_name }}-{{ version }}.tar.gz  # [py3k]
  url: https://pypi.io/packages/source/{{ pip_name[0] }}/{{ pip_name }}/{{ pip_name }}-{{ version }}.tar.gz  # [py3k]
  sha256: 3b63f24e6b04368c3e4a6f923f484be0230d821aad65ac36108edbff29e9aaab  # [py3k]

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - isort
    - pip
    - python
    - pycodestyle
  run:
    - python

test:
  imports:
    - avro
    - avro.schema

about:
  home: http://avro.apache.org
  license: Apache-2.0
  license_family: APACHE
  license_file: avro/LICENSE
  summary: Avro is a serialization and RPC framework.

extra:
  recipe-maintainers:
    - mariusvniekerk
    - kwilcox
    - setu4993
