{% set version = "1.9.0" %}
{% set mirror = "http://archive.apache.org/dist" %}

package:
  name: python-avro
  version: {{ version }}

source:  # [py27 or py3k]
  # Avro exist as two versions in apache avro for py2 and py3.
  fn: avro-{{ version }}.tar.gz  # [py27]
  url: {{ mirror }}/avro/avro-{{ version }}/py/avro-{{ version }}.tar.gz  # [py27]
  sha256: 'e4181a9dc686c82cbc9bb496787d659d55582c44ad74b69924c45f80f3d513a1'  # [py27]

  fn: avro-python3-{{ version }}.tar.gz  # [py3k]
  url: {{ mirror }}/avro/avro-{{ version }}/py3/avro-python3-{{ version }}.tar.gz  # [py3k]
  sha256: 'a3e698f09e702571bc2283471ed97f7055ae4c055a037624d04a95a320242ccf'  # [py3k]

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
  imports:
    - avro

about:
  home: http://avro.apache.org
  license: Apache 2.0
  summary: 'Avro is a serialization and RPC framework.'

extra:
  recipe-maintainers:
    - mariusvniekerk
    - kwilcox
