{% set pip_name = "avro" %}  # [py27]
{% set pip_name = "avro-python3" %}  # [py3k]
{% set version = "1.10.1" %}

package:
  name: python-avro
  version: {{ version }}

source:   # [py27 or py3k]
  # Avro exist as two versions in apache avro for py2 and py3k.
  fn: {{ pip_name }}-{{ version }}.tar.gz  # [py27]
  url: https://pypi.io/packages/source/{{ pip_name[0] }}/{{ pip_name }}/{{ pip_name }}-{{ version }}.tar.gz  # [py27]
  sha256: b3a405df5aa8654b992d2aca7b80482b858a1919a44dc0b10a682162e8ee340a  # [py27]

  fn: {{ pip_name }}-{{ version }}.tar.gz  # [py3k]
  url: https://pypi.io/packages/source/{{ pip_name[0] }}/{{ pip_name }}/{{ pip_name }}-{{ version }}.tar.gz  # [py3k]
  sha256: 9027abeab63dd9b66bd3c564fa0670c70f78027ecb1978d96c6af7ed415b626b  # [py3k]

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - isort
    - pip
    - python
    - pycodestyle
  run:
    - python

test:
  imports:
    - avro
    - avro.schema

about:
  home: http://avro.apache.org
  license: Apache-2.0
  license_family: APACHE
  license_file: avro/LICENSE
  summary: Avro is a serialization and RPC framework.

extra:
  recipe-maintainers:
    - mariusvniekerk
    - kwilcox
    - setu4993
